### ISSUE TITLE
[Crypto] Add Epic Cash

### ISSUE THREAD

**Issue by Den1ss** [haveno-dex/listing#32]
- [X] I confirm there are no other open issues about this asset
- [X] I understand that to actually add the asset to Haveno, a PR from the developers/community of the proposed asset might be necessary
- [X] I understand that adding the asset is at discretion of the Haveno Core Team and applying doesn't necessarily imply acceptance

### What's the ticker symbol of the project?
 EPIC

### Why should it be added to Haveno? How would it benefit the project and the community?

It would benefit the community by providing more diversification and offering a different type of protocol in Mimblewimble, which is also private by default and way more scalable than other protocols. 
It is also one of the most profitable coins for mining and has great potential, because its still in an early stage but is being actively developed by volunteers.

### Is it an Ethereum token (ERC-20)?

- [ ] Yes
- [X] No

### Was the coin pre-mined before public launch?

- [ ] Yes
- [X] No

### Is there a dev fee for the project maintainers?

- [X] Yes
- [ ] No

### Please provide resources about the project (Website, Twitter, etc)

All links are here -
https://epic.tech/community/

### Additional notes

Whitepaper - https://epic.tech/whitepaper/
